---
description: "Saiba mais sobre: ' Catch ' não pode aparecer após ' Finally ' dentro de uma instrução ' Try '"
title: "'Catch' não pode aparecer após 'Finally' dentro da instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454944"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' não pode aparecer após 'Finally' dentro da instrução 'Try'

Uma `Catch` instrução aparece no código após o `Finally` encerramento de um `Try` bloco de instrução. `Catch` deve aparecer dentro de um `Try...Catch...Finally` bloco de instruções.  
  
 **ID do erro:** BC30379  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Mova a `Catch` instrução para um local mais apropriado no código.  
  
## <a name="see-also"></a>Consulte também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
